### ISSUE TITLE
device not showing in device list

### ISSUE THREAD

**Issue by jschimmoeller** [fuzzysb/Garadget#7]
First thanks for this ST app; however when add my device I get the following error in the logs:

bf450a59-c07f-43ba-b6fe-9639c2e7661c  9:12:19 AM: debug getChildDevices(true), children=0
bf450a59-c07f-43ba-b6fe-9639c2e7661c  9:12:17 AM: debug Executing - Service Manager - poll() -
bf450a59-c07f-43ba-b6fe-9639c2e7661c  9:12:17 AM: debug Executing - Service Manager - poll() -
47b9bcac-ba6f-4d19-93d4-ad34a8a461ea  9:12:02 AM: trace getPhrases(), state.welcomeIssue = null
bf450a59-c07f-43ba-b6fe-9639c2e7661c  9:12:01 AM: debug getChildDevices(true), children=0
bf450a59-c07f-43ba-b6fe-9639c2e7661c  9:12:01 AM: debug Executing - Service Manager - poll() -
bf450a59-c07f-43ba-b6fe-9639c2e7661c  9:12:01 AM: error Error creating device: physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'Garadget' in namespace 'fuzzysb' not found. Garadget 4b0038000451353530353431:6e3881dba29a0aaea48c4af3b643405f3364f33d garage garage
bf450a59-c07f-43ba-b6fe-9639c2e7661c  9:12:01 AM: debug In createChildDevice
bf450a59-c07f-43ba-b6fe-9639c2e7661c  9:12:01 AM: debug getChildDevices(false), children=0

**Comment by jschimmoeller** [comment]
modified code to add logging of parameters:
log.error "Error creating device: ${e} ${deviceFile} ${dni} ${name} ${label}"

bf450a59-c07f-43ba-b6fe-9639c2e7661c 9:12:01 AM: error Error creating device: physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'Garadget' in namespace 'fuzzysb' not found. Garadget 4b0038000451353530353431:6e3881dba29a0aaea48c4af3b643405f3364f33d garage garage

**Comment by fuzzysb** [comment]
This is because you haven't installed the device handler. You've only installed the smart app.
Out of curiosity you are using the smartthings classic app? And not the new smartthings app as it doesn't support custom handlers

**Comment by jschimmoeller** [comment]
that solved it thanks. 

I am using the classic app only because I did not know; which check it out.
